#!/bin/bash
#
#  rabbitmq-common - common formula shell functions and config variables
#
#  Copyright (C) 2011  Canonical Ltd.
#  Author: Adam Gandelman <adam.gandelman@canonical.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

RABBIT_CTL='rabbitmqctl'
HOSTNAME=`hostname -f`
ERLANG_COOKIE="/var/lib/rabbitmq/.erlang.cookie"

function user_exists {
  $RABBIT_CTL list_users | grep $1 >/dev/null
}

function user_is_admin {
  $RABBIT_CTL list_users | grep $1 | grep true >/dev/null
}

function vhost_exists {
  $RABBIT_CTL list_vhosts | grep "^$VHOST\$" >/dev/null
}

function create_vhost {
  $RABBIT_CTL add_vhost $VHOST
}

function user_create {
  juju-log "rabbitmq: Creating user $1."

  $RABBIT_CTL add_user $1 $PASSWORD || return 1

  # grant the user all permissions on the default vhost /
  # TODO: investigate sane permissions
  juju-log "rabbitmq: Granting permission to $1 on vhost /"
  $RABBIT_CTL set_permissions -p $VHOST $1 ".*" ".*" ".*"

  if [[ $2 == 'admin' ]]  ; then
    user_is_admin $1 && return 0
    juju-log "rabbitmq: Granting user $1 admin access"
    $RABBIT_CTL set_admin $1 || return 1
  fi
}
